// usb20sr_refdes_mm_interconnect_1.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 15.0 139

`timescale 1 ps / 1 ps
module usb20sr_refdes_mm_interconnect_1 (
		input  wire        u20_clk_out_clk_clk,                             //                           u20_clk_out_clk.clk
		input  wire        ccb_usb_m0_reset_reset_bridge_in_reset_reset,    //    ccb_usb_m0_reset_reset_bridge_in_reset.reset
		input  wire        usb20sr_clock_reset_reset_bridge_in_reset_reset, // usb20sr_clock_reset_reset_bridge_in_reset.reset
		input  wire [20:0] ccb_usb_m0_address,                              //                                ccb_usb_m0.address
		output wire        ccb_usb_m0_waitrequest,                          //                                          .waitrequest
		input  wire [0:0]  ccb_usb_m0_burstcount,                           //                                          .burstcount
		input  wire [3:0]  ccb_usb_m0_byteenable,                           //                                          .byteenable
		input  wire        ccb_usb_m0_read,                                 //                                          .read
		output wire [31:0] ccb_usb_m0_readdata,                             //                                          .readdata
		output wire        ccb_usb_m0_readdatavalid,                        //                                          .readdatavalid
		input  wire        ccb_usb_m0_write,                                //                                          .write
		input  wire [31:0] ccb_usb_m0_writedata,                            //                                          .writedata
		input  wire        ccb_usb_m0_debugaccess,                          //                                          .debugaccess
		output wire [18:0] usb20sr_avalon_slave_0_address,                  //                    usb20sr_avalon_slave_0.address
		output wire        usb20sr_avalon_slave_0_write,                    //                                          .write
		output wire        usb20sr_avalon_slave_0_read,                     //                                          .read
		input  wire [31:0] usb20sr_avalon_slave_0_readdata,                 //                                          .readdata
		output wire [31:0] usb20sr_avalon_slave_0_writedata,                //                                          .writedata
		output wire [3:0]  usb20sr_avalon_slave_0_byteenable,               //                                          .byteenable
		input  wire        usb20sr_avalon_slave_0_readdatavalid,            //                                          .readdatavalid
		input  wire        usb20sr_avalon_slave_0_waitrequest,              //                                          .waitrequest
		output wire        usb20sr_avalon_slave_0_chipselect                //                                          .chipselect
	);

	wire         ccb_usb_m0_translator_avalon_universal_master_0_waitrequest;   // usb20sr_avalon_slave_0_translator:uav_waitrequest -> ccb_usb_m0_translator:uav_waitrequest
	wire  [31:0] ccb_usb_m0_translator_avalon_universal_master_0_readdata;      // usb20sr_avalon_slave_0_translator:uav_readdata -> ccb_usb_m0_translator:uav_readdata
	wire         ccb_usb_m0_translator_avalon_universal_master_0_debugaccess;   // ccb_usb_m0_translator:uav_debugaccess -> usb20sr_avalon_slave_0_translator:uav_debugaccess
	wire  [20:0] ccb_usb_m0_translator_avalon_universal_master_0_address;       // ccb_usb_m0_translator:uav_address -> usb20sr_avalon_slave_0_translator:uav_address
	wire         ccb_usb_m0_translator_avalon_universal_master_0_read;          // ccb_usb_m0_translator:uav_read -> usb20sr_avalon_slave_0_translator:uav_read
	wire   [3:0] ccb_usb_m0_translator_avalon_universal_master_0_byteenable;    // ccb_usb_m0_translator:uav_byteenable -> usb20sr_avalon_slave_0_translator:uav_byteenable
	wire         ccb_usb_m0_translator_avalon_universal_master_0_readdatavalid; // usb20sr_avalon_slave_0_translator:uav_readdatavalid -> ccb_usb_m0_translator:uav_readdatavalid
	wire         ccb_usb_m0_translator_avalon_universal_master_0_lock;          // ccb_usb_m0_translator:uav_lock -> usb20sr_avalon_slave_0_translator:uav_lock
	wire         ccb_usb_m0_translator_avalon_universal_master_0_write;         // ccb_usb_m0_translator:uav_write -> usb20sr_avalon_slave_0_translator:uav_write
	wire  [31:0] ccb_usb_m0_translator_avalon_universal_master_0_writedata;     // ccb_usb_m0_translator:uav_writedata -> usb20sr_avalon_slave_0_translator:uav_writedata
	wire   [2:0] ccb_usb_m0_translator_avalon_universal_master_0_burstcount;    // ccb_usb_m0_translator:uav_burstcount -> usb20sr_avalon_slave_0_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (21),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (21),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (1),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) ccb_usb_m0_translator (
		.clk                    (u20_clk_out_clk_clk),                                           //                       clk.clk
		.reset                  (ccb_usb_m0_reset_reset_bridge_in_reset_reset),                  //                     reset.reset
		.uav_address            (ccb_usb_m0_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (ccb_usb_m0_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (ccb_usb_m0_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (ccb_usb_m0_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (ccb_usb_m0_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (ccb_usb_m0_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (ccb_usb_m0_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (ccb_usb_m0_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (ccb_usb_m0_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (ccb_usb_m0_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (ccb_usb_m0_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (ccb_usb_m0_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (ccb_usb_m0_waitrequest),                                        //                          .waitrequest
		.av_burstcount          (ccb_usb_m0_burstcount),                                         //                          .burstcount
		.av_byteenable          (ccb_usb_m0_byteenable),                                         //                          .byteenable
		.av_read                (ccb_usb_m0_read),                                               //                          .read
		.av_readdata            (ccb_usb_m0_readdata),                                           //                          .readdata
		.av_readdatavalid       (ccb_usb_m0_readdatavalid),                                      //                          .readdatavalid
		.av_write               (ccb_usb_m0_write),                                              //                          .write
		.av_writedata           (ccb_usb_m0_writedata),                                          //                          .writedata
		.av_debugaccess         (ccb_usb_m0_debugaccess),                                        //                          .debugaccess
		.av_beginbursttransfer  (1'b0),                                                          //               (terminated)
		.av_begintransfer       (1'b0),                                                          //               (terminated)
		.av_chipselect          (1'b0),                                                          //               (terminated)
		.av_lock                (1'b0),                                                          //               (terminated)
		.uav_clken              (),                                                              //               (terminated)
		.av_clken               (1'b1),                                                          //               (terminated)
		.uav_response           (2'b00),                                                         //               (terminated)
		.av_response            (),                                                              //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                          //               (terminated)
		.av_writeresponsevalid  ()                                                               //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (19),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (21),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) usb20sr_avalon_slave_0_translator (
		.clk                    (u20_clk_out_clk_clk),                                           //                      clk.clk
		.reset                  (usb20sr_clock_reset_reset_bridge_in_reset_reset),               //                    reset.reset
		.uav_address            (ccb_usb_m0_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (ccb_usb_m0_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (ccb_usb_m0_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (ccb_usb_m0_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (ccb_usb_m0_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (ccb_usb_m0_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (ccb_usb_m0_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (ccb_usb_m0_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (ccb_usb_m0_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (ccb_usb_m0_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (ccb_usb_m0_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (usb20sr_avalon_slave_0_address),                                //      avalon_anti_slave_0.address
		.av_write               (usb20sr_avalon_slave_0_write),                                  //                         .write
		.av_read                (usb20sr_avalon_slave_0_read),                                   //                         .read
		.av_readdata            (usb20sr_avalon_slave_0_readdata),                               //                         .readdata
		.av_writedata           (usb20sr_avalon_slave_0_writedata),                              //                         .writedata
		.av_byteenable          (usb20sr_avalon_slave_0_byteenable),                             //                         .byteenable
		.av_readdatavalid       (usb20sr_avalon_slave_0_readdatavalid),                          //                         .readdatavalid
		.av_waitrequest         (usb20sr_avalon_slave_0_waitrequest),                            //                         .waitrequest
		.av_chipselect          (usb20sr_avalon_slave_0_chipselect),                             //                         .chipselect
		.av_begintransfer       (),                                                              //              (terminated)
		.av_beginbursttransfer  (),                                                              //              (terminated)
		.av_burstcount          (),                                                              //              (terminated)
		.av_writebyteenable     (),                                                              //              (terminated)
		.av_lock                (),                                                              //              (terminated)
		.av_clken               (),                                                              //              (terminated)
		.uav_clken              (1'b0),                                                          //              (terminated)
		.av_debugaccess         (),                                                              //              (terminated)
		.av_outputenable        (),                                                              //              (terminated)
		.uav_response           (),                                                              //              (terminated)
		.av_response            (2'b00),                                                         //              (terminated)
		.uav_writeresponsevalid (),                                                              //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                           //              (terminated)
	);

endmodule
