	DECA_Qsys u0 (
		.clk_clk                                       (<connected-to-clk_clk>),                                       //                                 clk.clk
		.ddr3_status_external_connection_export        (<connected-to-ddr3_status_external_connection_export>),        //     ddr3_status_external_connection.export
		.dipsw_pio_export                              (<connected-to-dipsw_pio_export>),                              //                           dipsw_pio.export
		.led_pio_export                                (<connected-to-led_pio_export>),                                //                             led_pio.export
		.mem_if_ddr3_emif_pll_ref_clk_clk              (<connected-to-mem_if_ddr3_emif_pll_ref_clk_clk>),              //        mem_if_ddr3_emif_pll_ref_clk.clk
		.mem_if_ddr3_emif_pll_sharing_pll_mem_clk      (<connected-to-mem_if_ddr3_emif_pll_sharing_pll_mem_clk>),      //        mem_if_ddr3_emif_pll_sharing.pll_mem_clk
		.mem_if_ddr3_emif_pll_sharing_pll_write_clk    (<connected-to-mem_if_ddr3_emif_pll_sharing_pll_write_clk>),    //                                    .pll_write_clk
		.mem_if_ddr3_emif_pll_sharing_pll_locked       (<connected-to-mem_if_ddr3_emif_pll_sharing_pll_locked>),       //                                    .pll_locked
		.mem_if_ddr3_emif_pll_sharing_pll_capture0_clk (<connected-to-mem_if_ddr3_emif_pll_sharing_pll_capture0_clk>), //                                    .pll_capture0_clk
		.mem_if_ddr3_emif_pll_sharing_pll_capture1_clk (<connected-to-mem_if_ddr3_emif_pll_sharing_pll_capture1_clk>), //                                    .pll_capture1_clk
		.mem_if_ddr3_emif_status_local_init_done       (<connected-to-mem_if_ddr3_emif_status_local_init_done>),       //             mem_if_ddr3_emif_status.local_init_done
		.mem_if_ddr3_emif_status_local_cal_success     (<connected-to-mem_if_ddr3_emif_status_local_cal_success>),     //                                    .local_cal_success
		.mem_if_ddr3_emif_status_local_cal_fail        (<connected-to-mem_if_ddr3_emif_status_local_cal_fail>),        //                                    .local_cal_fail
		.memory_mem_a                                  (<connected-to-memory_mem_a>),                                  //                              memory.mem_a
		.memory_mem_ba                                 (<connected-to-memory_mem_ba>),                                 //                                    .mem_ba
		.memory_mem_ck                                 (<connected-to-memory_mem_ck>),                                 //                                    .mem_ck
		.memory_mem_ck_n                               (<connected-to-memory_mem_ck_n>),                               //                                    .mem_ck_n
		.memory_mem_cke                                (<connected-to-memory_mem_cke>),                                //                                    .mem_cke
		.memory_mem_cs_n                               (<connected-to-memory_mem_cs_n>),                               //                                    .mem_cs_n
		.memory_mem_dm                                 (<connected-to-memory_mem_dm>),                                 //                                    .mem_dm
		.memory_mem_ras_n                              (<connected-to-memory_mem_ras_n>),                              //                                    .mem_ras_n
		.memory_mem_cas_n                              (<connected-to-memory_mem_cas_n>),                              //                                    .mem_cas_n
		.memory_mem_we_n                               (<connected-to-memory_mem_we_n>),                               //                                    .mem_we_n
		.memory_mem_reset_n                            (<connected-to-memory_mem_reset_n>),                            //                                    .mem_reset_n
		.memory_mem_dq                                 (<connected-to-memory_mem_dq>),                                 //                                    .mem_dq
		.memory_mem_dqs                                (<connected-to-memory_mem_dqs>),                                //                                    .mem_dqs
		.memory_mem_dqs_n                              (<connected-to-memory_mem_dqs_n>),                              //                                    .mem_dqs_n
		.memory_mem_odt                                (<connected-to-memory_mem_odt>),                                //                                    .mem_odt
		.nenet_reg_reset_export                        (<connected-to-nenet_reg_reset_export>),                        //                     nenet_reg_reset.export
		.pll_areset_conduit_export                     (<connected-to-pll_areset_conduit_export>),                     //                  pll_areset_conduit.export
		.pll_locked_conduit_export                     (<connected-to-pll_locked_conduit_export>),                     //                  pll_locked_conduit.export
		.pll_phasedone_conduit_export                  (<connected-to-pll_phasedone_conduit_export>),                  //               pll_phasedone_conduit.export
		.reset_reset_n                                 (<connected-to-reset_reset_n>),                                 //                               reset.reset_n
		.tse_mac_mac_mdio_connection_mdc               (<connected-to-tse_mac_mac_mdio_connection_mdc>),               //         tse_mac_mac_mdio_connection.mdc
		.tse_mac_mac_mdio_connection_mdio_in           (<connected-to-tse_mac_mac_mdio_connection_mdio_in>),           //                                    .mdio_in
		.tse_mac_mac_mdio_connection_mdio_out          (<connected-to-tse_mac_mac_mdio_connection_mdio_out>),          //                                    .mdio_out
		.tse_mac_mac_mdio_connection_mdio_oen          (<connected-to-tse_mac_mac_mdio_connection_mdio_oen>),          //                                    .mdio_oen
		.tse_mac_mac_mii_connection_mii_rx_d           (<connected-to-tse_mac_mac_mii_connection_mii_rx_d>),           //          tse_mac_mac_mii_connection.mii_rx_d
		.tse_mac_mac_mii_connection_mii_rx_dv          (<connected-to-tse_mac_mac_mii_connection_mii_rx_dv>),          //                                    .mii_rx_dv
		.tse_mac_mac_mii_connection_mii_rx_err         (<connected-to-tse_mac_mac_mii_connection_mii_rx_err>),         //                                    .mii_rx_err
		.tse_mac_mac_mii_connection_mii_tx_d           (<connected-to-tse_mac_mac_mii_connection_mii_tx_d>),           //                                    .mii_tx_d
		.tse_mac_mac_mii_connection_mii_tx_en          (<connected-to-tse_mac_mac_mii_connection_mii_tx_en>),          //                                    .mii_tx_en
		.tse_mac_mac_mii_connection_mii_tx_err         (<connected-to-tse_mac_mac_mii_connection_mii_tx_err>),         //                                    .mii_tx_err
		.tse_mac_mac_mii_connection_mii_crs            (<connected-to-tse_mac_mac_mii_connection_mii_crs>),            //                                    .mii_crs
		.tse_mac_mac_mii_connection_mii_col            (<connected-to-tse_mac_mac_mii_connection_mii_col>),            //                                    .mii_col
		.tse_mac_mac_misc_connection_ff_tx_crc_fwd     (<connected-to-tse_mac_mac_misc_connection_ff_tx_crc_fwd>),     //         tse_mac_mac_misc_connection.ff_tx_crc_fwd
		.tse_mac_mac_misc_connection_ff_tx_septy       (<connected-to-tse_mac_mac_misc_connection_ff_tx_septy>),       //                                    .ff_tx_septy
		.tse_mac_mac_misc_connection_tx_ff_uflow       (<connected-to-tse_mac_mac_misc_connection_tx_ff_uflow>),       //                                    .tx_ff_uflow
		.tse_mac_mac_misc_connection_ff_tx_a_full      (<connected-to-tse_mac_mac_misc_connection_ff_tx_a_full>),      //                                    .ff_tx_a_full
		.tse_mac_mac_misc_connection_ff_tx_a_empty     (<connected-to-tse_mac_mac_misc_connection_ff_tx_a_empty>),     //                                    .ff_tx_a_empty
		.tse_mac_mac_misc_connection_rx_err_stat       (<connected-to-tse_mac_mac_misc_connection_rx_err_stat>),       //                                    .rx_err_stat
		.tse_mac_mac_misc_connection_rx_frm_type       (<connected-to-tse_mac_mac_misc_connection_rx_frm_type>),       //                                    .rx_frm_type
		.tse_mac_mac_misc_connection_ff_rx_dsav        (<connected-to-tse_mac_mac_misc_connection_ff_rx_dsav>),        //                                    .ff_rx_dsav
		.tse_mac_mac_misc_connection_ff_rx_a_full      (<connected-to-tse_mac_mac_misc_connection_ff_rx_a_full>),      //                                    .ff_rx_a_full
		.tse_mac_mac_misc_connection_ff_rx_a_empty     (<connected-to-tse_mac_mac_misc_connection_ff_rx_a_empty>),     //                                    .ff_rx_a_empty
		.tse_mac_mac_status_connection_set_10          (<connected-to-tse_mac_mac_status_connection_set_10>),          //       tse_mac_mac_status_connection.set_10
		.tse_mac_mac_status_connection_set_1000        (<connected-to-tse_mac_mac_status_connection_set_1000>),        //                                    .set_1000
		.tse_mac_mac_status_connection_eth_mode        (<connected-to-tse_mac_mac_status_connection_eth_mode>),        //                                    .eth_mode
		.tse_mac_mac_status_connection_ena_10          (<connected-to-tse_mac_mac_status_connection_ena_10>),          //                                    .ena_10
		.tse_mac_pcs_mac_rx_clock_connection_clk       (<connected-to-tse_mac_pcs_mac_rx_clock_connection_clk>),       // tse_mac_pcs_mac_rx_clock_connection.clk
		.tse_mac_pcs_mac_tx_clock_connection_clk       (<connected-to-tse_mac_pcs_mac_tx_clock_connection_clk>),       // tse_mac_pcs_mac_tx_clock_connection.clk
		.user_pio_pushbtn_export                       (<connected-to-user_pio_pushbtn_export>)                        //                    user_pio_pushbtn.export
	);

