/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'nios2_gen2' in SOPC Builder design 'adc_qsys'
 * SOPC Builder design path: ../../adc_qsys.sopcinfo
 *
 * Generated: Mon May 04 14:58:57 CST 2015
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x00040820
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 50000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "fast"
#define ALT_CPU_DATA_ADDR_WIDTH 0x13
#define ALT_CPU_DCACHE_BYPASS_MASK 0x80000000
#define ALT_CPU_DCACHE_LINE_SIZE 32
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_DCACHE_SIZE 2048
#define ALT_CPU_EXCEPTION_ADDR 0x00020020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 50000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 1
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_EXTRA_EXCEPTION_INFO
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 32
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_ICACHE_SIZE 4096
#define ALT_CPU_INITDA_SUPPORTED
#define ALT_CPU_INST_ADDR_WIDTH 0x13
#define ALT_CPU_NAME "nios2_gen2"
#define ALT_CPU_NUM_OF_SHADOW_REG_SETS 0
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x00020000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x00040820
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 50000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "fast"
#define NIOS2_DATA_ADDR_WIDTH 0x13
#define NIOS2_DCACHE_BYPASS_MASK 0x80000000
#define NIOS2_DCACHE_LINE_SIZE 32
#define NIOS2_DCACHE_LINE_SIZE_LOG2 5
#define NIOS2_DCACHE_SIZE 2048
#define NIOS2_EXCEPTION_ADDR 0x00020020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 1
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_EXTRA_EXCEPTION_INFO
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 32
#define NIOS2_ICACHE_LINE_SIZE_LOG2 5
#define NIOS2_ICACHE_SIZE 4096
#define NIOS2_INITDA_SUPPORTED
#define NIOS2_INST_ADDR_WIDTH 0x13
#define NIOS2_NUM_OF_SHADOW_REG_SETS 0
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x00020000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_SYSID_QSYS
#define __ALTERA_AVALON_TIMER
#define __ALTERA_MODULAR_ADC
#define __ALTERA_NIOS2_GEN2
#define __ALTPLL


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "MAX 10"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/jtag_uart"
#define ALT_STDERR_BASE 0x41448
#define ALT_STDERR_DEV jtag_uart
#define ALT_STDERR_IS_JTAG_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_jtag_uart"
#define ALT_STDIN "/dev/jtag_uart"
#define ALT_STDIN_BASE 0x41448
#define ALT_STDIN_DEV jtag_uart
#define ALT_STDIN_IS_JTAG_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_jtag_uart"
#define ALT_STDOUT "/dev/jtag_uart"
#define ALT_STDOUT_BASE 0x41448
#define ALT_STDOUT_DEV jtag_uart
#define ALT_STDOUT_IS_JTAG_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_jtag_uart"
#define ALT_SYSTEM_NAME "adc_qsys"


/*
 * altpll_adc configuration
 *
 */

#define ALTPLL_ADC_BASE 0x41420
#define ALTPLL_ADC_IRQ -1
#define ALTPLL_ADC_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ALTPLL_ADC_NAME "/dev/altpll_adc"
#define ALTPLL_ADC_SPAN 16
#define ALTPLL_ADC_TYPE "altpll"
#define ALT_MODULE_CLASS_altpll_adc altpll


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 32
#define ALT_SYS_CLK TIMER
#define ALT_TIMESTAMP_CLK none


/*
 * jtag_uart configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart altera_avalon_jtag_uart
#define JTAG_UART_BASE 0x41448
#define JTAG_UART_IRQ 1
#define JTAG_UART_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_NAME "/dev/jtag_uart"
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_SPAN 8
#define JTAG_UART_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8


/*
 * modular_adc_0_sample_store_csr configuration
 *
 */

#define ALT_MODULE_CLASS_modular_adc_0_sample_store_csr altera_modular_adc
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_BASE 0x41200
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CORE_VARIANT 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_LENGTH 1
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_0 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_1 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_10 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_11 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_12 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_13 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_14 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_15 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_16 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_17 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_18 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_19 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_2 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_20 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_21 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_22 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_23 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_24 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_25 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_26 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_27 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_28 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_29 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_3 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_30 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_31 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_32 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_33 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_34 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_35 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_36 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_37 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_38 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_39 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_4 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_40 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_41 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_42 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_43 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_44 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_45 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_46 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_47 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_48 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_49 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_5 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_50 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_51 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_52 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_53 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_54 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_55 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_56 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_57 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_58 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_59 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_6 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_60 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_61 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_62 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_63 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_7 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_8 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_CSD_SLOT_9 "CH0"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_DUAL_ADC_MODE 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_IRQ -1
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_IS_THIS_FIRST_OR_SECOND_ADC 1
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_NAME "/dev/modular_adc_0_sample_store_csr"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_PRESCALER_CH16 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_PRESCALER_CH8 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_REFSEL "External VREF"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_SPAN 512
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_TYPE "altera_modular_adc"
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH0 1
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH1 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH10 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH11 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH12 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH13 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH14 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH15 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH16 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH2 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH3 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH4 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH5 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH6 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH7 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH8 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_CH9 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_USE_TSD 0
#define MODULAR_ADC_0_SAMPLE_STORE_CSR_VREF 2.5


/*
 * modular_adc_0_sequencer_csr configuration
 *
 */

#define ALT_MODULE_CLASS_modular_adc_0_sequencer_csr altera_modular_adc
#define MODULAR_ADC_0_SEQUENCER_CSR_BASE 0x41438
#define MODULAR_ADC_0_SEQUENCER_CSR_CORE_VARIANT 0
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_LENGTH 1
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_0 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_1 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_10 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_11 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_12 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_13 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_14 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_15 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_16 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_17 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_18 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_19 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_2 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_20 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_21 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_22 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_23 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_24 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_25 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_26 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_27 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_28 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_29 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_3 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_30 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_31 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_32 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_33 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_34 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_35 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_36 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_37 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_38 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_39 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_4 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_40 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_41 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_42 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_43 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_44 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_45 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_46 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_47 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_48 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_49 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_5 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_50 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_51 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_52 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_53 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_54 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_55 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_56 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_57 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_58 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_59 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_6 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_60 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_61 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_62 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_63 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_7 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_8 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_CSD_SLOT_9 "CH0"
#define MODULAR_ADC_0_SEQUENCER_CSR_DUAL_ADC_MODE 0
#define MODULAR_ADC_0_SEQUENCER_CSR_IRQ -1
#define MODULAR_ADC_0_SEQUENCER_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MODULAR_ADC_0_SEQUENCER_CSR_IS_THIS_FIRST_OR_SECOND_ADC 1
#define MODULAR_ADC_0_SEQUENCER_CSR_NAME "/dev/modular_adc_0_sequencer_csr"
#define MODULAR_ADC_0_SEQUENCER_CSR_PRESCALER_CH16 0
#define MODULAR_ADC_0_SEQUENCER_CSR_PRESCALER_CH8 0
#define MODULAR_ADC_0_SEQUENCER_CSR_REFSEL "External VREF"
#define MODULAR_ADC_0_SEQUENCER_CSR_SPAN 8
#define MODULAR_ADC_0_SEQUENCER_CSR_TYPE "altera_modular_adc"
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH0 1
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH1 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH10 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH11 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH12 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH13 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH14 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH15 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH16 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH2 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH3 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH4 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH5 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH6 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH7 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH8 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_CH9 0
#define MODULAR_ADC_0_SEQUENCER_CSR_USE_TSD 0
#define MODULAR_ADC_0_SEQUENCER_CSR_VREF 2.5


/*
 * modular_adc_1_sample_store_csr configuration
 *
 */

#define ALT_MODULE_CLASS_modular_adc_1_sample_store_csr altera_modular_adc
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_BASE 0x41000
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CORE_VARIANT 0
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_LENGTH 1
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_0 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_1 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_10 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_11 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_12 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_13 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_14 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_15 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_16 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_17 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_18 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_19 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_2 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_20 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_21 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_22 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_23 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_24 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_25 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_26 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_27 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_28 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_29 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_3 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_30 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_31 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_32 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_33 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_34 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_35 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_36 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_37 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_38 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_39 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_4 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_40 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_41 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_42 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_43 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_44 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_45 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_46 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_47 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_48 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_49 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_5 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_50 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_51 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_52 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_53 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_54 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_55 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_56 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_57 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_58 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_59 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_6 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_60 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_61 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_62 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_63 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_7 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_8 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_CSD_SLOT_9 "CH0"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_DUAL_ADC_MODE 0
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_IRQ -1
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_IS_THIS_FIRST_OR_SECOND_ADC 2
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_NAME "/dev/modular_adc_1_sample_store_csr"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_PRESCALER_CH16 0
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_PRESCALER_CH8 0
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_REFSEL "External VREF"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_SPAN 512
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_TYPE "altera_modular_adc"
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_USE_CH0 1
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_USE_CH1 0
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_USE_CH10 0
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_USE_CH11 0
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_USE_CH12 0
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_USE_CH13 0
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_USE_CH14 0
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_USE_CH15 0
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_USE_CH16 0
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_USE_CH2 0
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_USE_CH3 0
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_USE_CH4 0
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_USE_CH5 0
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_USE_CH6 0
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_USE_CH7 0
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_USE_CH8 0
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_USE_CH9 0
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_USE_TSD 0
#define MODULAR_ADC_1_SAMPLE_STORE_CSR_VREF 2.5


/*
 * modular_adc_1_sequencer_csr configuration
 *
 */

#define ALT_MODULE_CLASS_modular_adc_1_sequencer_csr altera_modular_adc
#define MODULAR_ADC_1_SEQUENCER_CSR_BASE 0x41430
#define MODULAR_ADC_1_SEQUENCER_CSR_CORE_VARIANT 0
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_LENGTH 1
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_0 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_1 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_10 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_11 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_12 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_13 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_14 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_15 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_16 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_17 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_18 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_19 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_2 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_20 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_21 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_22 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_23 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_24 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_25 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_26 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_27 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_28 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_29 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_3 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_30 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_31 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_32 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_33 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_34 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_35 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_36 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_37 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_38 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_39 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_4 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_40 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_41 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_42 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_43 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_44 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_45 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_46 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_47 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_48 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_49 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_5 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_50 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_51 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_52 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_53 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_54 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_55 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_56 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_57 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_58 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_59 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_6 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_60 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_61 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_62 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_63 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_7 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_8 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_CSD_SLOT_9 "CH0"
#define MODULAR_ADC_1_SEQUENCER_CSR_DUAL_ADC_MODE 0
#define MODULAR_ADC_1_SEQUENCER_CSR_IRQ -1
#define MODULAR_ADC_1_SEQUENCER_CSR_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MODULAR_ADC_1_SEQUENCER_CSR_IS_THIS_FIRST_OR_SECOND_ADC 2
#define MODULAR_ADC_1_SEQUENCER_CSR_NAME "/dev/modular_adc_1_sequencer_csr"
#define MODULAR_ADC_1_SEQUENCER_CSR_PRESCALER_CH16 0
#define MODULAR_ADC_1_SEQUENCER_CSR_PRESCALER_CH8 0
#define MODULAR_ADC_1_SEQUENCER_CSR_REFSEL "External VREF"
#define MODULAR_ADC_1_SEQUENCER_CSR_SPAN 8
#define MODULAR_ADC_1_SEQUENCER_CSR_TYPE "altera_modular_adc"
#define MODULAR_ADC_1_SEQUENCER_CSR_USE_CH0 1
#define MODULAR_ADC_1_SEQUENCER_CSR_USE_CH1 0
#define MODULAR_ADC_1_SEQUENCER_CSR_USE_CH10 0
#define MODULAR_ADC_1_SEQUENCER_CSR_USE_CH11 0
#define MODULAR_ADC_1_SEQUENCER_CSR_USE_CH12 0
#define MODULAR_ADC_1_SEQUENCER_CSR_USE_CH13 0
#define MODULAR_ADC_1_SEQUENCER_CSR_USE_CH14 0
#define MODULAR_ADC_1_SEQUENCER_CSR_USE_CH15 0
#define MODULAR_ADC_1_SEQUENCER_CSR_USE_CH16 0
#define MODULAR_ADC_1_SEQUENCER_CSR_USE_CH2 0
#define MODULAR_ADC_1_SEQUENCER_CSR_USE_CH3 0
#define MODULAR_ADC_1_SEQUENCER_CSR_USE_CH4 0
#define MODULAR_ADC_1_SEQUENCER_CSR_USE_CH5 0
#define MODULAR_ADC_1_SEQUENCER_CSR_USE_CH6 0
#define MODULAR_ADC_1_SEQUENCER_CSR_USE_CH7 0
#define MODULAR_ADC_1_SEQUENCER_CSR_USE_CH8 0
#define MODULAR_ADC_1_SEQUENCER_CSR_USE_CH9 0
#define MODULAR_ADC_1_SEQUENCER_CSR_USE_TSD 0
#define MODULAR_ADC_1_SEQUENCER_CSR_VREF 2.5


/*
 * onchip_memory2 configuration
 *
 */

#define ALT_MODULE_CLASS_onchip_memory2 altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_BASE 0x20000
#define ONCHIP_MEMORY2_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_DUAL_PORT 0
#define ONCHIP_MEMORY2_GUI_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY2_INIT_CONTENTS_FILE "adc_qsys_onchip_memory2"
#define ONCHIP_MEMORY2_INIT_MEM_CONTENT 0
#define ONCHIP_MEMORY2_INSTANCE_ID "NONE"
#define ONCHIP_MEMORY2_IRQ -1
#define ONCHIP_MEMORY2_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ONCHIP_MEMORY2_NAME "/dev/onchip_memory2"
#define ONCHIP_MEMORY2_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_RAM_BLOCK_TYPE "AUTO"
#define ONCHIP_MEMORY2_READ_DURING_WRITE_MODE "DONT_CARE"
#define ONCHIP_MEMORY2_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_SIZE_VALUE 128000
#define ONCHIP_MEMORY2_SPAN 128000
#define ONCHIP_MEMORY2_TYPE "altera_avalon_onchip_memory2"
#define ONCHIP_MEMORY2_WRITABLE 1


/*
 * sysid_qsys configuration
 *
 */

#define ALT_MODULE_CLASS_sysid_qsys altera_avalon_sysid_qsys
#define SYSID_QSYS_BASE 0x41440
#define SYSID_QSYS_ID 0
#define SYSID_QSYS_IRQ -1
#define SYSID_QSYS_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SYSID_QSYS_NAME "/dev/sysid_qsys"
#define SYSID_QSYS_SPAN 8
#define SYSID_QSYS_TIMESTAMP 1430722590
#define SYSID_QSYS_TYPE "altera_avalon_sysid_qsys"


/*
 * timer configuration
 *
 */

#define ALT_MODULE_CLASS_timer altera_avalon_timer
#define TIMER_ALWAYS_RUN 0
#define TIMER_BASE 0x41400
#define TIMER_COUNTER_SIZE 32
#define TIMER_FIXED_PERIOD 0
#define TIMER_FREQ 50000000
#define TIMER_IRQ 0
#define TIMER_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TIMER_LOAD_VALUE 49999
#define TIMER_MULT 0.001
#define TIMER_NAME "/dev/timer"
#define TIMER_PERIOD 1
#define TIMER_PERIOD_UNITS "ms"
#define TIMER_RESET_OUTPUT 0
#define TIMER_SNAPSHOT 1
#define TIMER_SPAN 32
#define TIMER_TICKS_PER_SEC 1000
#define TIMER_TIMEOUT_PULSE_OUTPUT 0
#define TIMER_TYPE "altera_avalon_timer"

#endif /* __SYSTEM_H_ */
